title: HPC Summer School 2018
subtitle: Compute Ontario Summer School on Technical and High-Performance Computing
registration: https://www.eventbrite.ca/e/hpc-summer-school-2018-tickets-47264500393
author: Centre for Advanced Computing
baseurl: /summer-school-2018
# or future-dated posts won't show up
future: true
