title: HPC Summer School 2018
subtitle: Compute Ontario Summer School on Technical and High-Performance Computing
registration: /summer-school-2018/registration-closed.html
author: Centre for Advanced Computing
baseurl: /summer-school-2018
